### ISSUE TITLE
Point DNS to Heroku app?

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-status#3]
Shall we have status.openaerialmap.org point to https://oam-status.herokuapp.com and link it from the homepage and browser?

**Comment by smit1678** [comment]
@cgiovando Following up here. Yes, agree. Can you point a `CNAME` record for `status` on the DNS to `oam-status.herokuapp.com`?

**Comment by cgiovando** [comment]
Added

![screen shot 2015-07-30 at 10 19 00](https://cloud.githubusercontent.com/assets/10201533/8990023/9574e4fe-36a4-11e5-8a09-d75f1f1b32ae.png)
